name: Python application

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      NUSER: ${{ secrets.NUSER }}
      NPASS: ${{ secrets.NPASS }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run application
      run: |
        python3 main.py
